//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFCalculator.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        double add(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        System.Threading.Tasks.Task<double> addAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sub", ReplyAction="http://tempuri.org/IService1/subResponse")]
        double sub(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sub", ReplyAction="http://tempuri.org/IService1/subResponse")]
        System.Threading.Tasks.Task<double> subAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mul", ReplyAction="http://tempuri.org/IService1/mulResponse")]
        double mul(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/mul", ReplyAction="http://tempuri.org/IService1/mulResponse")]
        System.Threading.Tasks.Task<double> mulAsync(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/div", ReplyAction="http://tempuri.org/IService1/divResponse")]
        double div(double num1, double num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/div", ReplyAction="http://tempuri.org/IService1/divResponse")]
        System.Threading.Tasks.Task<double> divAsync(double num1, double num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCFCalculator.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFCalculator.ServiceReference2.IService1>, WCFCalculator.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double num1, double num2) {
            return base.Channel.add(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double num1, double num2) {
            return base.Channel.addAsync(num1, num2);
        }
        
        public double sub(double num1, double num2) {
            return base.Channel.sub(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> subAsync(double num1, double num2) {
            return base.Channel.subAsync(num1, num2);
        }
        
        public double mul(double num1, double num2) {
            return base.Channel.mul(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> mulAsync(double num1, double num2) {
            return base.Channel.mulAsync(num1, num2);
        }
        
        public double div(double num1, double num2) {
            return base.Channel.div(num1, num2);
        }
        
        public System.Threading.Tasks.Task<double> divAsync(double num1, double num2) {
            return base.Channel.divAsync(num1, num2);
        }
    }
}
